# Generated by Django 4.2.3 on 2023-07-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_empreendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=15)),
                ('quartos', models.IntegerField(blank=True, null=True)),
                ('valor_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField()),
                ('limite_ideal', models.IntegerField(blank=True, null=True)),
                ('limite_adicional', models.IntegerField(blank=True, null=True)),
                ('aceita_pet', models.BooleanField(default=False)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.empreendimento')),
            ],
        ),
    ]
