# Generated by Django 4.2.3 on 2023-07-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_acomodacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoObservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.tipoobservacao')),
            ],
        ),
    ]
