# Generated by Django 4.2.3 on 2023-07-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_dadoscliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dados_adicionais',
            field=models.BooleanField(default=False),
        ),
    ]
