# Generated by Django 4.2.3 on 2023-07-13 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_cliente_dados_adicionais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('checkin', models.CharField(max_length=100)),
                ('data_saida', models.DateField()),
                ('checkout', models.CharField(max_length=100)),
                ('data_orcamento', models.DateField(default=django.utils.timezone.now)),
                ('n_ocupantes', models.IntegerField()),
                ('n_dias', models.IntegerField()),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=7)),
                ('taxa_limpeza', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('acrescimos', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('valor_pacote', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('dias_pacote', models.IntegerField(default=0)),
                ('diaria_cheia', models.BooleanField(default=False)),
                ('periodo', models.CharField(max_length=100)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.acomodacao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
            ],
        ),
    ]
