# Generated by Django 4.2.3 on 2023-07-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_horario_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.TextField()),
                ('condicoes_pagamento', models.TextField()),
                ('informacoes_adicionais', models.TextField()),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.orcamento')),
            ],
        ),
    ]
