# Generated by Django 4.2.3 on 2023-07-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_orcamento_contrato_gerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='n_ocupantes',
            field=models.IntegerField(default=0),
        ),
    ]
