# Generated by Django 4.2.3 on 2023-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_orcamento_eliminado_orcamento_finalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='dia_entrada',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='dia_saida',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
