# Generated by Django 4.2.3 on 2023-07-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_orcamento_dia_entrada_orcamento_dia_saida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='contrato_gerado',
            new_name='modificado',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='obs_modificacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='obs_n_ocupantes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('em digitação', 'em digitação'), ('digitação concluída', 'digitação concluída'), ('orçamento gerado', 'orçamento gerado'), ('contrato gerado', 'contrato gerado')], default='em digitação', max_length=20),
            preserve_default=False,
        ),
    ]
