# Generated by Django 4.2.3 on 2023-07-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_rename_contrato_gerado_orcamento_modificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
