# Generated by Django 4.2.3 on 2023-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_alter_orcamento_valor_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='img_orcamento',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='total_valor_reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
