# Generated by Django 4.2.3 on 2023-07-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_orcamento_img_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='img_contrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='img_orcamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
