# Generated by Django 4.2.3 on 2023-07-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_alter_orcamento_img_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='img_contrato',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='img_orcamento',
        ),
    ]
