# Generated by Django 4.2.3 on 2023-07-21 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_contrato',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
