# Generated by Django 4.2.3 on 2023-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_contrato_data_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
