# Generated by Django 4.2.3 on 2023-07-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_alter_acomodacao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
