# Generated by Django 4.2.3 on 2023-07-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_lancamentos_delete_depositos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamentos',
            old_name='tipo_lancamento',
            new_name='tipo',
        ),
    ]
