# Generated by Django 4.2.3 on 2023-07-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0027_rename_tipo_lancamento_lancamentos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
