# Generated by Django 4.2.3 on 2023-07-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0028_orcamento_valor_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='quitado',
            field=models.BooleanField(default=False),
        ),
    ]
